# Generated by Django 4.0 on 2022-09-17 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetics_brand_image',
            name='Cosmetics_brand_image_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 49, 14, 87047)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Newsletter_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 49, 14, 86049)),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='perchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 49, 14, 91036)),
        ),
        migrations.AlterField(
            model_name='stay_updated_subscribtion',
            name='Stay_Updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 49, 14, 87047)),
        ),
        migrations.AlterField(
            model_name='video_post',
            name='Blog_podt_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 49, 14, 85053)),
        ),
    ]
