# Generated by Django 4.0 on 2022-09-17 20:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_one', '0003_alter_cosmetics_brand_image_cosmetics_brand_image_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetics_brand_image',
            name='Cosmetics_brand_image_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 51, 15, 522876)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Newsletter_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 51, 15, 521878)),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='User_Connect_with_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='perchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 51, 15, 526864)),
        ),
        migrations.AlterField(
            model_name='stay_updated_subscribtion',
            name='Stay_Updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 51, 15, 521878)),
        ),
        migrations.AlterField(
            model_name='video_post',
            name='Blog_podt_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 2, 51, 15, 520881)),
        ),
    ]
