# Generated by Django 4.0 on 2022-09-18 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_alter_cosmetics_brand_image_cosmetics_brand_image_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Table',
            },
        ),
        migrations.AlterField(
            model_name='cosmetics_brand_image',
            name='Cosmetics_brand_image_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 12, 47, 15, 93524)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Newsletter_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 12, 47, 15, 91446)),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='perchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 12, 47, 15, 97432)),
        ),
        migrations.AlterField(
            model_name='stay_updated_subscribtion',
            name='Stay_Updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 12, 47, 15, 91446)),
        ),
        migrations.AlterField(
            model_name='video_post',
            name='Blog_podt_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 12, 47, 15, 90450)),
        ),
    ]
