# Generated by Django 4.0 on 2022-09-18 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_contact_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cosmetics_brand_image',
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Newsletter_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 13, 30, 25, 734978)),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='perchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 13, 30, 25, 740962)),
        ),
        migrations.AlterField(
            model_name='stay_updated_subscribtion',
            name='Stay_Updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 13, 30, 25, 735975)),
        ),
        migrations.AlterField(
            model_name='video_post',
            name='Blog_podt_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 13, 30, 25, 734978)),
        ),
    ]
